After upgradin to hyperopt 0.2.1, I'ev got the error 'AttributeError: module 'bson' has no attribute 'BSON''. Solved by removing bson and adding pymongo: pip uninstall bson && pip install pymongo